site_url = ""
site_name = "Tyler Trout's Blog"
site_motto = "Full Stack Web Development"
footer_note = "Build Good Stuff"
media_dir = "media"
build_dir = "_build"
theme = "simple"
theme_root_dir = "_themes"
rebuild_interval = 2
posts_per_page = 20
